name: SSL Certificate Request and Post

on:
  schedule:
    - cron: '0 0 */60 * *'  # 每60天执行一次
  workflow_dispatch:  # 支持手动触发

env:
  DOMAIN1: ${{ secrets.DOMAIN1 }}
  DOMAIN2: ${{ secrets.DOMAIN2 }}
  URL: ${{ secrets.URL }}
  PHPSESSID: ${{ secrets.PHPSESSID }}
  A: ${{ secrets.A }}
  C: ${{ secrets.C }}
  

jobs:
  ssl_certificate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Certbot
        run: |
          echo "DOMAIN3: $DOMAIN1"
          echo "DOMAIN4: $DOMAIN2"
          echo "URL: $URL"
