name: SSL Certificate Request and Post

on:
  schedule:
    - cron: '0 0 */60 * *'  # 每60天执行一次
  workflow_dispatch:  # 支持手动触发

env:
  DOMAIN1: ${{ secrets.DOMAIN1 }}
  DOMAIN2: ${{ secrets.DOMAIN2 }}
  TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
  TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
  EMAIL: ${{ secrets.EMAIL }}  # 从 GitHub Secrets 中获取电子邮件
  LOGIN_URL: ${{ secrets.LOGIN_URL }}
  REFER_URL: ${{ secrets.REFER_URL }}
  URL: ${{ secrets.URL }}
  LOGOUT_URL: ${{ secrets.LOGOUT_URL }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  certificate: ${{ secrets.CERTIFICATE }}
  certificate_key: ${{ secrets.CERTIFICATE_KEY }}

jobs:
  ssl_certificate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Certbot and DNS Plugin (Tencent Cloud)
        run: |
          # 更新 apt 源
          sudo apt update
          
          # 安装 Certbot
          sudo apt install -y certbot python3-pip

          # 使用 pip 安装 certbot-dns-tcloud 插件
          sudo pip install git+https://github.com/tengattack/certbot-dns-dnspod.git  
          
      - name: Request SSL certificate with DNS-01 challenge
        run: |
          # 创建腾讯云的配置文件，保存 API 密钥
          sudo echo "dns_dnspod_api_id = $TENCENT_CLOUD_SECRET_ID" >> /tmp/tcloud.ini
          sudo echo "dns_dnspod_api_token = $TENCENT_CLOUD_SECRET_KEY" >> /tmp/tcloud.ini
          sudo chmod 600 /tmp/tcloud.ini  # 确保文件权限安全
          # 打印域名值进行调试
          echo "DOMAIN1: $DOMAIN1"
          echo "DOMAIN2: $DOMAIN2"

          # 使用 DNS-01 挑战通过腾讯云插件申请证书
          sudo certbot certonly --staging -a dns-dnspod \
            --dns-dnspod-credentials /tmp/tcloud.ini \
            -d $DOMAIN1 -d $DOMAIN2 \
            --agree-tos --email $EMAIL --non-interactive
            
      - name: Post SSL certificate information and capture response
        run: |
          sudo chmod -R 755 /etc/letsencrypt/live/
          certificate=$(sudo cat /etc/letsencrypt/live/$DOMAIN1/fullchain.pem)
          certificate_key=$(sudo cat /etc/letsencrypt/live/$DOMAIN1/privkey.pem)

          echo "certificate: $certificate; certificate_key: $certificate_key"

          # 通过 curl 登录，并保存cookie信息
          curl -c cookies.txt -X POST $LOGIN_URL \
                  -H "Content-Type: application/x-www-form-urlencoded" \
                  -H "User-Agent: Mozilla/5.0" \
                  -H "Referer: $REFER_URL" \
                  -d "username=$USERNAME&passwd=$PASSWORD"
          
          # 通过 curl 发起 POST 请求，并将结果保存到变量
          response=$(curl -X POST $URL \
                  -F "certificate=$certificate" \
                  -F "certificate_key=$certificate_key" \
                  -b cookies.txt \
                  -v)

          # 输出 curl 请求的响应结果到 GitHub Actions 日志
          echo "Curl response: $response"

          # 通过 curl 登出，并保存cookie信息
          curl -b cookies.txt $LOGOUT_URL
          
